const C=window.VIGYAPAN_CONFIG||{};let TOKEN=sessionStorage.getItem('vigyapan_admin_token')||'';let DATA={};const $=s=>document.querySelector(s);
const schemas={
 services:[['ID','text'],['TITLE','text'],['DESCRIPTION','text'],['ICON','text'],['ACTIVE','select:YES|NO'],['SORT','number']],
 plans:[['ID','text'],['TITLE','text'],['MONTHS','number'],['PRICE','number'],['OLD_PRICE','number'],['SHOW_PRICE','select:YES|NO'],['OFFER_TEXT','text'],['FEATURES','textarea'],['HIGHLIGHT','text'],['ACTIVE','select:YES|NO'],['SORT','number']],
 gallery:[['ID','text'],['TITLE','text'],['TYPE','select:IMAGE|VIDEO'],['URL','text'],['THUMB_URL','text'],['SORT','number'],['ACTIVE','select:YES|NO']],
 products:[['ID','text'],['NAME','text'],['CATEGORY','text'],['DESCRIPTION','textarea'],['PRICE','number'],['OLD_PRICE','number'],['IMAGE_URL','text'],['ACTIVE','select:YES|NO'],['SORT','number']],
 socials:[['ID','text'],['LABEL','text'],['URL','text'],['ICON','text'],['ACTIVE','select:YES|NO'],['SORT','number']]
};
document.addEventListener('DOMContentLoaded',()=>{if(TOKEN)loadAdmin();$('#loginForm').onsubmit=login;$('#logout').onclick=()=>{sessionStorage.removeItem('vigyapan_admin_token');location.reload()};$('#saveSettings').onclick=saveSettings;$('#passwordForm').onsubmit=changePassword;$('#uploadGallery').onclick=uploadGallery;$('#uploadProduct').onclick=uploadProduct;$('#uploadLogo').onclick=uploadLogo;$('#uploadFooter').onclick=uploadFooter;});
async function api(body){if(!C.API_URL||C.API_URL.includes('PASTE_'))throw new Error('config.js me Apps Script URL paste karo.');const r=await fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j;}
async function login(e){e.preventDefault();const f=new FormData(e.target);$('#loginMsg').textContent='Checking...';try{const r=await api({action:'login',username:f.get('username'),password:f.get('password')});TOKEN=r.token;sessionStorage.setItem('vigyapan_admin_token',TOKEN);loadAdmin();}catch(x){$('#loginMsg').textContent=x.message;}}
async function loadAdmin(){try{const r=await api({action:'adminBootstrap',token:TOKEN});DATA=r.data;$('#login').style.display='none';$('#app').style.display='block';buildTabs();renderAll();}catch(e){sessionStorage.removeItem('vigyapan_admin_token');$('#login').style.display='block';$('#app').style.display='none';$('#loginMsg').textContent=e.message;}}
function buildTabs(){const a=[['settings','Website'],['services','Services'],['plans','Plans'],['gallery','Gallery / Slider'],['products','Products'],['socials','Social / Buttons'],['leads','Enquiries'],['orders','Orders']];$('#tabs').innerHTML=a.map((x,i)=>`<button class="tab ${i===0?'active':''}" onclick="showTab('${x[0]}',this)">${x[1]}</button>`).join('');}
function showTab(id,b){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#panel-'+id).classList.add('active');}
function renderAll(){renderSettings();renderTable('services');renderTable('plans');renderTable('gallery');renderTable('products');renderTable('socials');renderReadOnly('leads');renderReadOnly('orders');}
const settingsKeys=[['brand_name','Brand Name'],['tagline','Tagline'],['phone1','Phone 1'],['phone2','Phone 2'],['email','Email'],['address','Address'],['map_embed','Google Maps Embed URL'],['instagram','Instagram URL'],['facebook','Facebook URL'],['twitter','Twitter URL'],['whatsapp','WhatsApp Number (country code, no +)'],['logo_url','Logo URL'],['hero_title','Home Hero Title'],['hero_text','Home Hero Text'],['about_title','About Title'],['about_text','About Text'],['footer_text','Footer Text'],['footer_image_url','Footer Image URL'],['order_note','Order WhatsApp Intro']];
function renderSettings(){$('#settingsForm').innerHTML=settingsKeys.map(([k,l])=>`<div class="field ${['about_text','hero_text','footer_text'].includes(k)?'full':''}"><label>${l}</label>${['about_text','hero_text','footer_text'].includes(k)?`<textarea class="textarea" data-setting="${k}">${esc(DATA.settings?.[k]||'')}</textarea>`:`<input class="input" data-setting="${k}" value="${escAttr(DATA.settings?.[k]||'')}">`}</div>`).join('');}
async function saveSettings(){const items={};document.querySelectorAll('[data-setting]').forEach(x=>items[x.dataset.setting]=x.value);try{await api({action:'saveSettings',token:TOKEN,items});toast('Website settings saved');}catch(e){toast(e.message)}}
async function changePassword(e){e.preventDefault();const f=new FormData(e.target);try{await api({action:'changeAdminPassword',token:TOKEN,oldPassword:f.get('old'),newPassword:f.get('new')});toast('Password changed');e.target.reset();}catch(x){toast(x.message)}}
function renderTable(key){const rows=DATA[key]||[];const sc=schemas[key];let h='<div class="table-wrap"><table class="atable"><thead><tr>'+sc.map(x=>`<th>${x[0]}</th>`).join('')+'<th>Action</th></tr></thead><tbody>';rows.forEach((r,i)=>{h+=`<tr data-row="${key}-${i}">`+sc.map(([k,t])=>`<td>${fieldHtml(k,t,r[k])}</td>`).join('')+`<td><button class="btn btn-dark" onclick="saveRow('${key}',${i})">Save</button> <button class="btn danger" onclick="deleteRow('${key}',${i})">Delete</button></td></tr>`});h+='</tbody></table></div>';$('#'+key+'Table').innerHTML=h;}
function fieldHtml(k,t,v){v=v??'';if(t.startsWith('select:'))return `<select data-k="${k}">${t.slice(7).split('|').map(o=>`<option ${String(v)===o?'selected':''}>${o}</option>`).join('')}</select>`;if(t==='textarea')return `<textarea data-k="${k}" rows="3">${esc(v)}</textarea>`;return `<input data-k="${k}" type="${t}" value="${escAttr(v)}">`;}
async function saveRow(key,i){const row=(DATA[key]||[])[i];const tr=document.querySelector(`[data-row="${key}-${i}"]`);const obj={};tr.querySelectorAll('[data-k]').forEach(x=>obj[x.dataset.k]=x.value);try{await api({action:'saveRows',token:TOKEN,sheet:key.toUpperCase(),rows:[obj]});Object.assign(row,obj);toast('Saved');}catch(e){toast(e.message)}}
async function deleteRow(key,i){if(!confirm('Delete this item?'))return;try{await api({action:'deleteRow',token:TOKEN,sheet:key.toUpperCase(),id:(DATA[key]||[])[i].ID});DATA[key].splice(i,1);renderTable(key);toast('Deleted');}catch(e){toast(e.message)}}
function addRow(key){const sc=schemas[key],obj={ID:key.slice(0,2).toUpperCase()+Date.now().toString().slice(-6),ACTIVE:'YES',SORT:(DATA[key]?.length||0)+1};sc.forEach(([k])=>{if(obj[k]===undefined)obj[k]='';});if(key==='plans'){obj.SHOW_PRICE='NO';obj.FEATURES='';obj.HIGHLIGHT='';}if(key==='services')obj.ICON='◆';if(key==='socials')obj.ICON='link';if(key==='gallery')obj.TYPE='IMAGE';DATA[key].push(obj);renderTable(key);toast('New row added. Fill it and Save.');}
async function uploadFooter(){const f=$('#footerFile').files[0];if(!f)return toast('Select footer image');try{const d=await compressImage(f);const r=await api({action:'uploadMedia',token:TOKEN,fileName:'footer.webp',mimeType:d.mimeType,base64:d.base64,folder:'Branding'});await api({action:'saveSettings',token:TOKEN,items:{footer_image_url:r.url}});DATA.settings.footer_image_url=r.url;renderSettings();toast('Footer image uploaded & saved');}catch(e){toast(e.message)}}
async function uploadLogo(){const f=$('#logoFile').files[0];if(!f)return toast('Select logo image');try{const d=await compressImage(f);const r=await api({action:'uploadMedia',token:TOKEN,fileName:'logo.webp',mimeType:d.mimeType,base64:d.base64,folder:'Branding'});await api({action:'saveSettings',token:TOKEN,items:{logo_url:r.url}});DATA.settings.logo_url=r.url;renderSettings();toast('Logo uploaded & saved');}catch(e){toast(e.message)}}
async function uploadGallery(){const f=$('#galleryFile').files[0];if(!f)return toast('Select a file');const title=$('#galleryTitle').value||f.name;try{toast('Preparing upload...');const data=await prepareFile(f);const r=await api({action:'uploadMedia',token:TOKEN,fileName:data.name,mimeType:data.mimeType,base64:data.base64,folder:'Gallery'});const row={ID:'G'+Date.now(),TITLE:title,TYPE:f.type.startsWith('video')?'VIDEO':'IMAGE',URL:r.url,THUMB_URL:r.thumb,SORT:(DATA.gallery?.length||0)+1,ACTIVE:'YES'};await api({action:'saveRows',token:TOKEN,sheet:'GALLERY',rows:[row]});DATA.gallery.push(row);renderTable('gallery');renderAll();toast('Gallery media uploaded & saved');$('#galleryFile').value='';$('#galleryTitle').value='';}catch(e){toast(e.message)}}
async function uploadProduct(){const f=$('#productFile').files[0];if(!f)return toast('Select an image');const id=$('#productId').value.trim();try{const data=await prepareFile(f);const r=await api({action:'uploadMedia',token:TOKEN,fileName:data.name,mimeType:data.mimeType,base64:data.base64,folder:'Products'});if(id){const row=DATA.products.find(x=>x.ID===id);if(!row)throw new Error('Product ID not found');row.IMAGE_URL=r.url;await api({action:'saveRows',token:TOKEN,sheet:'PRODUCTS',rows:[row]});}else{const row={ID:'PR'+Date.now().toString().slice(-7),NAME:f.name.replace(/\.[^.]+$/,''),CATEGORY:'',DESCRIPTION:'',PRICE:'',OLD_PRICE:'',IMAGE_URL:r.url,ACTIVE:'YES',SORT:(DATA.products?.length||0)+1};DATA.products.push(row);await api({action:'saveRows',token:TOKEN,sheet:'PRODUCTS',rows:[row]});}renderTable('products');toast('Product image saved');}catch(e){toast(e.message)}}
async function prepareFile(f){if(f.type.startsWith('image/'))return compressImage(f);return await fileToBase64(f);}
function fileToBase64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({base64:r.result,name:f.name,mimeType:f.type});r.onerror=rej;r.readAsDataURL(f);});}
function compressImage(f){return new Promise((resolve,reject)=>{const im=new Image(),r=new FileReader();r.onload=()=>{im.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);let data=c.toDataURL('image/webp',.72);if(data.length<1000)data=c.toDataURL('image/jpeg',.72);resolve({base64:data,name:f.name.replace(/\.[^.]+$/,'')+'.webp',mimeType:data.startsWith('data:image/webp')?'image/webp':'image/jpeg'});};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(f);});}
function renderReadOnly(key){const rows=DATA[key]||[];if(!rows.length){$('#'+key+'Table').innerHTML='<p class="muted">No records yet.</p>';return}const headers=Object.keys(rows[0]);$('#'+key+'Table').innerHTML='<div class="table-wrap"><table class="atable"><thead><tr>'+headers.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+headers.map(h=>`<td>${esc(r[h])}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>';}
function toast(t){const x=$('#toast');x.textContent=t;x.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>x.style.display='none',2600)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(v){return esc(v)}
