const C=window.VIGYAPAN_CONFIG||{};let TOKEN=sessionStorage.getItem('vigyapan_admin_token')||'',DATA={};const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const schemas={
 services:[['ID','text'],['TITLE','text'],['DESCRIPTION','textarea'],['ICON','text'],['IMAGE_URL','text'],['ACTIVE','select:YES|NO'],['SORT','number']],
 plans:[['ID','text'],['TITLE','text'],['MONTHS','number'],['PRICE','number'],['OLD_PRICE','number'],['SHOW_PRICE','select:YES|NO'],['OFFER_TEXT','text'],['FEATURES','textarea'],['HIGHLIGHT','text'],['ACTIVE','select:YES|NO'],['SORT','number']],
 gallery:[['ID','text'],['TITLE','text'],['TYPE','select:IMAGE|VIDEO'],['URL','text'],['THUMB_URL','text'],['SORT','number'],['ACTIVE','select:YES|NO']],
 products:[['ID','text'],['NAME','text'],['CATEGORY','text'],['DESCRIPTION','textarea'],['PRICE','number'],['OLD_PRICE','number'],['IMAGE_URL','text'],['IMAGE_URL_2','text'],['IMAGE_URL_3','text'],['IMAGE_URL_4','text'],['IMAGE_URL_5','text'],['ACTIVE','select:YES|NO'],['SORT','number']],
 socials:[['ID','text'],['LABEL','text'],['URL','text'],['ICON','text'],['ACTIVE','select:YES|NO'],['SORT','number']]
};
const settingsKeys=[
 ['brand_name','Brand Name'],['tagline','Tagline'],['phone1','Phone 1'],['phone2','Phone 2'],['email','Email'],['address','Address'],
 ['map_embed','Google Maps Embed / iframe code'],['map_link','Google Maps full link / directions URL'],
 ['instagram','Instagram URL'],['facebook','Facebook URL'],['twitter','Twitter / X URL'],['whatsapp','WhatsApp Number (country code, no +)'],
 ['hero_title','Hero Title'],['hero_text','Hero Text'],['about_title','About Title'],['about_text','About Text'],['footer_text','Footer Text'],['order_note','WhatsApp enquiry intro']
];

document.addEventListener('DOMContentLoaded',()=>{
 if(TOKEN)loadAdmin();$('#loginForm').onsubmit=login;$('#logout').onclick=()=>{sessionStorage.removeItem('vigyapan_admin_token');location.reload()};
 $('#saveSettings').onclick=saveSettings;$('#passwordForm').onsubmit=changePassword;$('#uploadGallery').onclick=uploadGallery;$('#uploadProduct').onclick=uploadProduct;
 $('#uploadLogo').onclick=uploadLogo;$('#uploadHero').onclick=uploadHero;$('#uploadShowcase').onclick=uploadShowcase;$('#uploadService').onclick=uploadService;
});
async function api(body){if(!C.API_URL||C.API_URL.includes('PASTE_'))throw new Error('config.js me Apps Script URL paste karo.');const r=await fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j;}
async function login(e){e.preventDefault();const f=new FormData(e.target);$('#loginMsg').textContent='Checking...';try{const r=await api({action:'login',username:f.get('username'),password:f.get('password')});TOKEN=r.token;sessionStorage.setItem('vigyapan_admin_token',TOKEN);loadAdmin();}catch(x){$('#loginMsg').textContent=x.message;}}
async function loadAdmin(){try{const r=await api({action:'adminBootstrap',token:TOKEN});DATA=r.data||{};$('#login').style.display='none';$('#app').style.display='block';buildTabs();renderAll();}catch(e){sessionStorage.removeItem('vigyapan_admin_token');TOKEN='';$('#login').style.display='block';$('#app').style.display='none';$('#loginMsg').textContent=e.message;}}
function buildTabs(){const a=[['settings','Website'],['services','Services'],['plans','Packages'],['gallery','Gallery'],['products','Work / Products'],['socials','Social Icons'],['leads','Enquiries'],['orders','Work Enquiries']];$('#tabs').innerHTML=a.map((x,i)=>`<button class="tab ${i===0?'active':''}" onclick="showTab('${x[0]}',this)">${x[1]}</button>`).join('');}
function showTab(id,b){$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#panel-'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function renderAll(){renderSettings();renderTable('services');renderTable('plans');renderTable('gallery');renderTable('products');renderTable('socials');renderReadOnly('leads');renderReadOnly('orders');renderShowcaseList();}
function renderSettings(){const areas=['map_embed','map_link','hero_text','about_text','footer_text','order_note'];$('#settingsForm').innerHTML=settingsKeys.map(([k,l])=>`<div class="field ${areas.includes(k)?'full':''}"><label>${l}</label>${areas.includes(k)?`<textarea class="textarea" data-setting="${k}">${esc(DATA.settings?.[k]||'')}</textarea>`:`<input class="input" data-setting="${k}" value="${escAttr(DATA.settings?.[k]||'')}">`}</div>`).join('');}
async function saveSettings(){const items={};document.querySelectorAll('[data-setting]').forEach(x=>items[x.dataset.setting]=x.value);try{await api({action:'saveSettings',token:TOKEN,items});Object.assign(DATA.settings,items);toast('Website settings saved');}catch(e){toast(e.message)}}
async function changePassword(e){e.preventDefault();const f=new FormData(e.target);try{await api({action:'changeAdminPassword',token:TOKEN,oldPassword:f.get('old'),newPassword:f.get('new')});toast('Password changed');e.target.reset();}catch(x){toast(x.message)}}
function renderTable(key){const rows=DATA[key]||[],sc=schemas[key];let h='<div class="table-wrap"><table class="atable"><thead><tr>'+sc.map(x=>`<th>${x[0]}</th>`).join('')+'<th>Action</th></tr></thead><tbody>';rows.forEach((r,i)=>{h+=`<tr data-row="${key}-${i}">`+sc.map(([k,t])=>`<td>${fieldHtml(k,t,r[k])}</td>`).join('')+`<td><button class="btn btn-dark" onclick="saveRow('${key}',${i})">Save</button> <button class="btn danger" onclick="deleteRow('${key}',${i})">Delete</button></td></tr>`});h+='</tbody></table></div>';$('#'+key+'Table').innerHTML=h;}
function fieldHtml(k,t,v){v=v??'';if(t.startsWith('select:'))return `<select data-k="${k}">${t.slice(7).split('|').map(o=>`<option ${String(v)===o?'selected':''}>${o}</option>`).join('')}</select>`;if(t==='textarea')return `<textarea data-k="${k}" rows="3">${esc(v)}</textarea>`;return `<input data-k="${k}" type="${t}" value="${escAttr(v)}">`;}
async function saveRow(key,i){const row=(DATA[key]||[])[i],tr=document.querySelector(`[data-row="${key}-${i}"]`),obj={};tr.querySelectorAll('[data-k]').forEach(x=>obj[x.dataset.k]=x.value);try{await api({action:'saveRows',token:TOKEN,sheet:key.toUpperCase(),rows:[obj]});Object.assign(row,obj);toast('Saved');}catch(e){toast(e.message)}}
async function deleteRow(key,i){if(!confirm('Delete this item?'))return;try{await api({action:'deleteRow',token:TOKEN,sheet:key.toUpperCase(),id:(DATA[key]||[])[i].ID});DATA[key].splice(i,1);renderTable(key);toast('Deleted');}catch(e){toast(e.message)}}
function addRow(key){const sc=schemas[key],obj={ID:key.slice(0,2).toUpperCase()+Date.now().toString().slice(-6),ACTIVE:'YES',SORT:(DATA[key]?.length||0)+1};sc.forEach(([k])=>{if(obj[k]===undefined)obj[k]='';});if(key==='plans'){obj.SHOW_PRICE='NO';obj.FEATURES='';obj.HIGHLIGHT='';}if(key==='services')obj.ICON='◆';if(key==='socials')obj.ICON='link';if(key==='gallery')obj.TYPE='IMAGE';DATA[key].push(obj);renderTable(key);toast('New row added. Fill it and Save.');}

function driveId(url){const s=String(url||'');const m=s.match(/[?&]id=([A-Za-z0-9_-]+)/)||s.match(/\/d\/([A-Za-z0-9_-]+)/);return m?m[1]:'';}
async function uploadAndReturn(file,folder,prefix,replaceDriveId=''){const d=await prepareFile(file);return api({action:'uploadMedia',token:TOKEN,fileName:prefix+'_'+Date.now()+'.webp',mimeType:d.mimeType,base64:d.base64,folder,replaceDriveId});}
async function uploadLogo(){const f=$('#logoFile').files[0];if(!f)return toast('Select logo image');try{const r=await uploadAndReturn(f,'Branding','logo',driveId(DATA.settings.logo_url));await api({action:'saveSettings',token:TOKEN,items:{logo_url:r.url}});DATA.settings.logo_url=r.url;renderSettings();toast('Logo replaced and saved');$('#logoFile').value='';}catch(e){toast(e.message)}}
async function uploadHero(){const f=$('#heroFile').files[0];if(!f)return toast('Select hero image');try{const r=await uploadAndReturn(f,'Branding','hero-cover',driveId(DATA.settings.hero_image_url));await api({action:'saveSettings',token:TOKEN,items:{hero_image_url:r.url}});DATA.settings.hero_image_url=r.url;renderSettings();toast('Hero replaced and saved');$('#heroFile').value='';}catch(e){toast(e.message)}}
async function uploadShowcase(){const files=[...($('#showcaseFiles').files||[])];if(!files.length)return toast('Select one or more images');try{let urls=String(DATA.settings.showcase_urls||'').split('|').map(x=>x.trim()).filter(Boolean);for(const f of files){const r=await uploadAndReturn(f,'Showcase','showcase');urls.push(r.url);}urls=urls.slice(-30);await api({action:'saveSettings',token:TOKEN,items:{showcase_urls:urls.join('|')}});DATA.settings.showcase_urls=urls.join('|');renderShowcaseList();$('#showcaseFiles').value='';toast(files.length+' showcase image(s) added');}catch(e){toast(e.message)}}
function renderShowcaseList(){const urls=String(DATA.settings?.showcase_urls||'').split('|').map(x=>x.trim()).filter(Boolean);$('#showcaseList').innerHTML=urls.length?urls.map((u,i)=>`<div class="showcase-item"><img src="${escAttr(mediaUrl(u))}" onerror="this.style.display='none'"><button title="Remove" onclick="removeShowcase(${i})">×</button></div>`).join(''):'<div class="muted small">No dedicated showcase images yet. Gallery photos will be used as a fallback on the public site.</div>';}
async function removeShowcase(i){const urls=String(DATA.settings?.showcase_urls||'').split('|').map(x=>x.trim()).filter(Boolean);if(!urls[i])return;if(!confirm('Remove this image from the showcase?'))return;urls.splice(i,1);try{await api({action:'saveSettings',token:TOKEN,items:{showcase_urls:urls.join('|')}});DATA.settings.showcase_urls=urls.join('|');renderShowcaseList();toast('Removed from showcase');}catch(e){toast(e.message)}}
function mediaId(u){const s=String(u||'');const m=s.match(/[?&]id=([A-Za-z0-9_-]+)/)||s.match(/\/d\/([A-Za-z0-9_-]+)/);return m?m[1]:'';}
function mediaUrl(u){const id=mediaId(u);return id?'https://lh3.googleusercontent.com/d/'+id+'=w500':u;}
async function uploadService(){const f=$('#serviceFile').files[0],id=$('#serviceId').value.trim();if(!f||!id)return toast('Select image and enter Service ID');try{const row=DATA.services.find(x=>x.ID===id);if(!row)throw new Error('Service ID not found');const r=await uploadAndReturn(f,'Services','service',driveId(row.IMAGE_URL));row.IMAGE_URL=r.url;await api({action:'saveRows',token:TOKEN,sheet:'SERVICES',rows:[row]});renderTable('services');$('#serviceFile').value='';toast('Service image saved');}catch(e){toast(e.message)}}
async function uploadGallery(){const f=$('#galleryFile').files[0];if(!f)return toast('Select a file');const title=$('#galleryTitle').value||f.name;try{toast('Uploading...');const data=await prepareFile(f),r=await api({action:'uploadMedia',token:TOKEN,fileName:data.name,mimeType:data.mimeType,base64:data.base64,folder:'Gallery'});const row={ID:'G'+Date.now(),TITLE:title,TYPE:f.type.startsWith('video')?'VIDEO':'IMAGE',URL:r.url,THUMB_URL:r.thumb,SORT:(DATA.gallery?.length||0)+1,ACTIVE:'YES'};await api({action:'saveRows',token:TOKEN,sheet:'GALLERY',rows:[row]});DATA.gallery.push(row);renderTable('gallery');$('#galleryFile').value='';$('#galleryTitle').value='';toast('Gallery media uploaded');}catch(e){toast(e.message)}}
async function uploadProduct(){const files=[...($('#productFiles').files||[])];if(!files.length)return toast('Select one or more photos');let id=$('#productId').value.trim();try{for(const f of files){const data=await prepareFile(f),r=await api({action:'uploadMedia',token:TOKEN,fileName:data.name,mimeType:data.mimeType,base64:data.base64,folder:'Products'});if(!id){const row={ID:'PR'+Date.now().toString().slice(-7),NAME:f.name.replace(/\.[^.]+$/,''),CATEGORY:'',DESCRIPTION:'',PRICE:'',OLD_PRICE:'',IMAGE_URL:r.url,IMAGE_URL_2:'',IMAGE_URL_3:'',IMAGE_URL_4:'',IMAGE_URL_5:'',ACTIVE:'YES',SORT:(DATA.products?.length||0)+1};await api({action:'saveRows',token:TOKEN,sheet:'PRODUCTS',rows:[row]});DATA.products.push(row);id=row.ID;}else{const row=DATA.products.find(x=>x.ID===id);if(!row)throw new Error('Work ID not found');const keys=['IMAGE_URL','IMAGE_URL_2','IMAGE_URL_3','IMAGE_URL_4','IMAGE_URL_5'];const slot=keys.find(k=>!row[k]);if(!slot)throw new Error('Maximum 5 photos already uploaded for this work.');row[slot]=r.url;await api({action:'saveRows',token:TOKEN,sheet:'PRODUCTS',rows:[row]});}}renderTable('products');$('#productFiles').value='';toast('Photo(s) saved');}catch(e){toast(e.message)}}
function prepareFile(f){return f.type.startsWith('image/')?compressImage(f):fileToBase64(f);}
function fileToBase64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({base64:r.result,name:f.name,mimeType:f.type});r.onerror=rej;r.readAsDataURL(f);});}
function compressImage(f){return new Promise((resolve,reject)=>{const im=new Image(),r=new FileReader();r.onload=()=>{im.onload=()=>{let max=1600;const make=(q,m)=>{const scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));const ctx=c.getContext('2d');ctx.drawImage(im,0,0,c.width,c.height);return c.toDataURL('image/webp',q)};let data='';for(const q of [.78,.68,.58,.48,.40,.34]){data=make(q);if(data.length<=125000)break;}while(data.length>125000&&max>700){max-=150;data=make(.42);}if(data.length>125000)throw new Error('Image could not be compressed below 100 KB. Try a simpler image.');resolve({base64:data,name:f.name.replace(/\.[^.]+$/,'')+'.webp',mimeType:'image/webp'});};im.onerror=reject;im.src=r.result;};r.onerror=reject;r.readAsDataURL(f);});}
function renderReadOnly(key){const rows=DATA[key]||[];if(!rows.length){$('#'+key+'Table').innerHTML='<p class="muted">No records yet.</p>';return}const headers=Object.keys(rows[0]);$('#'+key+'Table').innerHTML='<div class="table-wrap"><table class="atable"><thead><tr>'+headers.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+headers.map(h=>`<td>${esc(r[h])}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>';}
function toast(t){const x=$('#toast');x.textContent=t;x.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>x.style.display='none',3000)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(v){return esc(v).replace(/`/g,'&#96;')}
